### ISSUE TITLE
Fixed: added and removed some quotation marks at login.html

### ISSUE THREAD

**Issue by gejobj** [benmfaul/XRTB#10]
I have fixed some quotation marks in HTML code.
You can see them and apply from here:
https://github.com/gejobj/XRTB/commit/8fab4c86c3cd62e0c6146986181b57a1286d5bb3

**Comment by benmfaul** [comment]
Thank you, I applied your fix.

-Ben Faul

**Comment by gejobj** [comment]
Thank you for your great work! ;-)
