### ISSUE TITLE
cast error in the simulator exchange for Smaato / Native (App Wall)

### ISSUE THREAD

**Issue by lionux2** [benmfaul/XRTB#4]
Having issue to test the current simulator: getting X-TIME: 3, RTT: 0, **\* NO BID **\* REASON: Server stopped.

But for some reasons, for the Smaato / Native (App Wall), I have this error?

java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
        at com.xrtb.pojo.BidRequest.setup(BidRequest.java:529)
        at com.xrtb.pojo.BidRequest.<init>(BidRequest.java:323)
        at com.xrtb.exchanges.Smaato.<init>(Smaato.java:48)
        at com.xrtb.exchanges.Smaato.copy(Smaato.java:59)
        at com.xrtb.exchanges.Smaato.copy(Smaato.java:19)
        at com.xrtb.bidder.Handler.handle(RTBServer.java:707)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
{
  "id" : "9db3e877-5719-14f6-c24e-5b7ae02b110b",
  "at" : 2,
  "imp" : [ {
    "id" : "9db3e877-5719-14f6-c24e-5b7ae02b110b",
    "instl" : 0,
    "native" : {
      "layout" : 2,
      "assets" : [ {
        "id" : 1,
        "required" : 1,
        "title" : {
          "len" : 30
        }
      }, {
        "id" : 2,
        "required" : 0,
        "data" : {
          "type" : 3,
          "len" : 5
        }
      }, {
        "id" : 3,
        "required" : 1,
        "img" : {
          "type" : 1,
          "w" : 64,
          "h" : 64,
          "mimes" : "image/png"
        }
      }, {
        "id" : 4,
        "required" : 0,
        "data" : {
          "type" : 2,
          "len" : 10
        }
      } ]
    },
    "ext" : {
      "nex_screen" : 0
    }
  } ],
  "site" : {
    "id" : "99201",
    "name" : "BidderTestMobileWEB",
    "domain" : "junk1.com",
    "cat" : [ "IAB1", "IAB2" ],
    "keywords" : "radiation",
    "page" : "http://www.nexage.com",
    "ref" : "http://www.iab.net",
    "search" : "radiation",
    "publisher" : {
      "id" : "98401",
      "name" : "testme"
    },
    "ext" : {
      "nex_coppa" : 0
    },
    "gender" : "F"
  },
  "device" : {
    "didsha1" : "132079238ec783b0b89dff308e1f9bdd08576273",
    "dpidsha1" : "f22711a823044bb9ce7ace097955de0286eb0182",
    "ip" : "166.137.138.18",
    "carrier" : "ATT",
    "ua" : "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; el-gr) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5",
    "make" : "Apple",
    "model" : "iPhone",
    "osv" : "3.1.2",
    "connectiontype" : 3,
    "devicetype" : 1,
    "geo" : {
      "lat" : 42.378,
      "lon" : -71.227,
      "country" : "USA"
    }
  },
  "user" : {
    "id" : "ASDFJKL",
    "yob" : 1961,
    "gender" : "F",
    "keywords" : "sports",
    "geo" : {
      "country" : "USA",
      "city" : "Waltham",
      "zip" : "02451",
      "region" : "MA",
      "type" : 3
    },
    "ext" : {
      "nex_eth" : "4",
      "nex_marital" : "M",
      "nex_kids" : "N",
      "nex_hhi" : 75000,
      "nex_dma" : "Boston"
    }
  },
  "ext" : {
    "coppa" : 0,
    "udi" : {
      "googleadid" : "5e2efab6-7721-4cfe-b542-97084d5aa62f",
      "googlednt" : 0,
      "atuid" : "a90377ab-190b-1036-f424-ac10fdb8ffef"
    },
    "operaminibrowser" : 0,
    "carriername" : "Verizon Wireless"
  }
}

**Comment by benmfaul** [comment]
Hello:

I will look into this within the next day and respond to you. Thanks.

Ben Faul.

**Comment by benmfaul** [comment]
Lionux:

Problem 1:
On the SMAATO test, were you running the curl script
smaatoCompliance/smaatoImageTest.sh? In that particular test you showed me,
the
server is operational, but stopped means it is not set to process. Can you
send me your Campaigns/payday.json file?

Thanks.

-------------------------------------

Problem 2:
A Patch to correct the problem of the missing node on AppWall:
Edit the file  com.xrtb.pojo.BidRequest for the time being until I can
fully test:
At Line 528 the code looks like this:
                                                               if
(child.path("mimes") instanceof MissingNode == false) {
array = (ArrayNode) child.path("mimes");                         //
for (JsonNode nx : array) {
nativePart.img.mimes
.add(nx.textValue());
}
}

Change it to:
====================================

if (child.path("mimes") instanceof MissingNode == false) {
if (child.path("mimes") instanceof TextNode) {
nativePart.img.mimes.add(child.get("mimes").asText());
} else {
array = (ArrayNode) child.path("mimes");
for (JsonNode nx : array) {
nativePart.img.mimes
.add(nx.textValue());
}
}
}

I will check the code changes in shortly.

-Ben

**Comment by lionux2** [comment]
Dear Ben;

I was running it from the web interface ... the simulator.

I will try to test it via the curl script, and know that I did not 
change any Campaigns/payday.json.

Honestly, I think I might not have done the right step for my testing.

Tonight, I will try again, and come back to you.

By the way, thanks very much for your email, and looking at those 
issues. My colleague will also jump into testing it soon.

Thanks,

P.

**Comment by lionux2** [comment]
Dear Ben;

This is my file

$more payday.json

{
        "seats": [
                {
                        "name": "adprudence",
                        "id": "adprudenceid",
                        "bid": "/rtb/bids/adprudence=com.xrtb.exchanges.Adprudence"
                },
                {
                        "name": "atomx",
                        "id": "atomxseatid",
                        "bid": "/rtb/bids/atomx=com.xrtb.exchanges.Atomx"
                },
                {
                        "name": "smartyads",
                        "id": "smartypants",
                        "bid": "/rtb/bids/smartyads=com.xrtb.exchanges.Smartyads"
                },
                {
                        "name": "nexage",
                        "id": "99999999",
                        "bid": "/rtb/bids/nexage=com.xrtb.exchanges.Nexage"
                },
                {
                        "name": "privatex",
                        "id": "5555555",
                        "bid": "/rtb/bids/privatex=com.xrtb.exchanges.Privatex"
                },
                {
                        "name": "fyber",
                        "id": "seat1",
                        "bid": "/rtb/bids/fyber=com.xrtb.exchanges.Fyber"
                },
                {
                        "name": "smaato",
                        "id": "seat1",
                        "bid": "/rtb/bids/smaato=com.xrtb.exchanges.Smaato"
                },
                {
                        "name": "epomx",
                        "id": "seat1",
                        "bid": "/rtb/bids/epomx=com.xrtb.exchanges.Epomx"
                },
                {
                        "name": "cappture",
                        "id": "capptureseatid",
                        "bid": "/rtb/bids/cappture=com.xrtb.exchanges.Cappture"
                }
        ],

        "forensiq": {
                "threshhold": 0,
                "ck": "none",
                "endpoint": "http://api.forensiq.com/check",
                "bidOnError": false
        },

        "app": {
                "password": "startrekisbetterthanstarwars",
                "deadmanswitch": "accountingsystem",
                "stopped": false,
                "ttl": 300,
                "pixel-tracking-url": "http://localhost:8080/pixel",
                "winurl": "http://localhost:8080/rtb/win",
                "redirect-url": "http://localhost:8080/redirect",
                "verbosity": {
                        "level": -3,
                        "nobid-reason": false
                },
                "NOgeotags": {
                        "states": "data/zip_codes_states.csv",
                        "zipcodes": "data/unique_geo_zipcodes.txt"
                },
                "zeromq": {
                        "bidchannel": "tcp://*:5571&bids",
                        "winchannel": "tcp://*:5572&wins",
                        "clicks": "tcp://*:5573&clicks",
                        "logger": "tcp://*:5574&logs",
                        "responses": "tcp://*:5575&responses",
                        "pixels": "tcp://*:5576&pixels",
                        "NOforensiq": "file://logs/forensiq",
                        "NOrequests": "file://logs/request",
                        "subscribers": {
                                "hosts": [
                                        "localhost",
                                        "192.168.0.48"
                                ],
                                "commands": "5580"
                        }
                },
                "aerospike": {
                        "host": "localhost",
                        "port": 3000
                },
                "template": {
                        "default": "<a href='{redirect_url}/{pub}/{ad_id}/{creative_id}/${AUCTION_PRICE}/{lat}/{lon}?u
rl={creative_forward_url}'><img src='{pixel_url}/{pub}/{ad_id}/{creative_id}/{bid_id}/${AUCTION_PRICE}/{lat}/{lon}' he
ight='1' width='1'><img src='{creative_image_url}' height='{creative_ad_height}' width='{creative_ad_width}'></a>",
                        "exchange": {
                                "mopub": "<a href='mopub template here' </a>",
                                "mobclix": "<a href='mobclix template here' </a>",
                                "nexage": "<a href='{redirect_url}/exchange={pub}/ad_id={ad_id}/creative_id={creative_
id}/price=${AUCTION_PRICE}/lat={lat}/lon={lon}/bid_id={bid_id}?url={creative_forward_url}'><img src='{creative_image_u
rl}' height='{creative_ad_height}' width='{creative_ad_width}'></a><img src='{pixel_url}/exchange={pub}/ad_id={ad_id}/
creative_id={creative_id}/{bid_id}/price=${AUCTION_PRICE}/lat={lat}/lon={lon}/bid_id={bid_id}' height='1' width='1'>",

                                "smartyads": "{creative_forward_url}",
                                "atomx": "{creative_forward_url}",
                                "epomx": "{creative_forward_url}",
                                "cappture": "cappture/{creative_forward_url}",
                                "privatex": "<a href='{redirect_url}/{pub}/{ad_id}/{creative_id}/${AUCTION_PRICE}/{lat
}/{lon}?url={creative_forward_url}'><img src='{pixel_url}/{pub}/{ad_id}/{bid_id}/{creative_id}/${AUCTION_PRICE}/{lat}/
{lon}' height='1' width='1'><img src='{creative_image_url}' height='{creative_ad_height}' width='{creative_ad_width}'>
</a>",
                                "smaato": "richMediaBeacon='%%smaato_ct_url%%'; script='{creative_forward_url}'; click
url='{redirect_url}/exchange={pub}/{ad_id}/creative_id={creative_id}/price=${AUCTION_PRICE}/lat={lat}/lon={lon}/bid_id
={bid_id}?url={creative_forward_url}'; imageurl='{creative_image_url}'; pixelurl='{pixel_url}/exchange={pub}/ad_id={ad
_id}/creative_id={creative_id}/{bid_id}/price=${AUCTION_PRICE}/lat={lat}/lon={lon}/bid_id={bid_id}';"
                        }
                },
                "campaigns": [
                        {
                                "name": "ben",
                                "id": "ben:payday"
                        }
                ]
        }
}

nothing special: however, when I run tools/rtb4free
I have this message: ... ?

[2016-10-09 01:30:46.457] - 1 - default - DeadmanSwitch - Switch error: accountingsystem, does not exist, no bidding allowed!
[2016-10-09 01:30:46.461] - 1 - default - stopBidder - Bidder stopped by command from default

Also, the curl script does nothing. no log from tools/rtb4free except +1 for requests, and +1 for nobids.
So, I suppose that those two messages above are the problems.
Thanks,

P.

**Comment by benmfaul** [comment]
Lionux:

Ok, the other problem is fixed.

This is a config problem. I inadvertently checked in payday.json with the
app object "deafmanswitch": .... This means if the aerospike key
"deadmanswitch" is not present, the bidder won't bid. This is used when a
database system is cnfiguring RTB, if an external program is doing
accounting and it crashes, the deadmanswitch will expire and the bidder
should stop. Otherwise, you would lose all your accounting data

But you don't need that. just change "deadmanswitxh" to "NOdeadmanswitch"
and it will correct that issue.

Or do a git pull and this should correct all your issues.

Thanks for sending me the errrors.

-Ben Faul
ben.faul@gmail.com
RTB4FREE.COM
