### ISSUE TITLE
"add a new exchange" instruction for RTB4FREE

### ISSUE THREAD

**Issue by lionux2** [benmfaul/XRTB#5]
Hi Ben;

I have been playing with RTB4FREE, and I am running some integration with a new exchange, which worked well apart from two things:
1) looking into the process, it worked although "mvn" to rebuild the java bidder was not mentioned (obvious, still worth adding I think).
2) on line 66 of payday.json, there is an error: cappture should be taggify I believe:
		{
			"name": "taggify",
			"id": "taggifyid",
			"bid": "/rtb/bids/cappture=com.xrtb.exchanges.Taggify"
		}
I copied this line and change Taggify into the name of my new exchange, and of course, I had "Handler:handle:error - Wrong target: /rtb/bids/xxxx". I realized later, much later, that is was because I copied the line with an error in it.

Thanks,

Lionux.

**Comment by benmfaul** [comment]
You are correct.

I will update the code for this.

Thanks.

-Ben Faul
