### ISSUE TITLE
Connect to  Smaato  Status: Test failed

### ISSUE THREAD

**Issue by ruanlp** [benmfaul/XRTB#8]
Hello, I follow
Step by step www.rtb4free.com/smaato.html
Status: Test failed
Error message:
Your server returned a "no bid" response when it was expected to return a valid bid.
Context information:

URL used to request your server = http://45.56.95.67/rtb/bids/smaato?testbid=bid
Ad type(s) requested = Txt

{
  "at":2,
  "device":{
    "connectiontype":0,
    "devicetype":1,
    "geo":{
      "lat":42.357777,
      "lon":-71.06167,
      "type":1
    },
    "ip":"201.252.0.0",
    "js":0,
    "make":"Apple",
    "model":"iPhone",
    "os":"iOS",
    "osv":"1.2.3",
    "ua":"Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16"
  },
  "ext":{
    "coppa":0,
    "operaminibrowser":0,
    "udi":{ }
  },
  "id":"8xaQKCskPe",
  "imp":[
    {
      "banner":{
        "btype":[
          2,
          3
        ],
        "h":20,
        "mimes":[
          "text/html",
          "text/plain"
        ],
        "w":120
      },
      "displaymanager":"SOMA",
      "id":"1",
      "instl":0
    }
  ],
  "site":{
    "cat":[
      "IAB1"
    ],
    "domain":"www.jacksbar.co.uk",
    "id":"0",
    "name":"Jack Rabbit Slims",
    "publisher":{
      "id":"6"
    }
  },
  "user":{
    "gender":"M",
    "yob":1983
  }
}

**Comment by benmfaul** [comment]
Hello:

Your bidder is in 'no-bid mode'. Campaigns/payday.json has an incorrect
value in it.

1. Edit Campaigns/payday.json

2. Look for the "app.stopped". It is probably set to true

3. Change it to false. Should look something  like this:
"app" : {
    "stopped" : false,
    "ttl" : 300,
    "deadmanswitch" : null,
    "multibid" : false,
.....

When true it means when the bidder comes up it is no bid mode.

4. Restart your bidder.

The default Campaigns/payday.json was checked in with the wrong value. If
you git pull it will be corrected for you.

Thanks for letting me know.

-Ben Faul
RTB4FREE.COM
Jacamars, Inc.
